name: "sandbox ci"

env:
  GO_VERSION: 1.15
  MINIKUBE_VERSION: v1.18.1
  KUBERNETES_VERSION: v1.19.6

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Minikube:
    name: Deploy Sandbox and Run UI Automation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: '${{ env.MINIKUBE_VERSION }}'
          kubernetes version: '${{ env.KUBERNETES_VERSION }}'
          start args: '--addons=ingress'
      - name: Deploy Trustbloc
        run: |
          minikube ip
          kubectl get nodes
          make ci-setup-deploy
      - name: Run UI-test
        run: |
          make automation-test
